[package]
name = "restaurant_review"
version = "0.1.0"
description = "Native Solana Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
borsh = "1.5.1"
solana-program = "1.16.24"
thiserror = "1.0.48"
